/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns the health status and current version of the API.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Sales & Product Data
         * @description Upload a CSV or Excel file to generate in-memory data profiling, ABC/Pareto product ranking, period growth trends, and chart-ready JSON.
         */
        post: operations["analyze_data_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ABCDistributionItemResponse
         * @description ABC distribution breakdown item.
         */
        ABCDistributionItemResponse: {
            /**
             * Abc Class
             * @description ABC Class (A, B, or C)
             * @example A
             */
            abc_class: string;
            /**
             * Product Count
             * @description Number of products in class
             * @example 3
             */
            product_count: number;
            /**
             * Value
             * @description Total monetary value for class
             * @example 750000
             */
            value: number;
            /**
             * Value Share Pct
             * @description Percentage share of total value
             * @example 78.5
             */
            value_share_pct: number;
        };
        /**
         * ABCSummaryResponse
         * @description Summary metrics per ABC category.
         */
        ABCSummaryResponse: {
            /**
             * Class A Count
             * @description Number of Class A products
             * @example 3
             */
            class_a_count: number;
            /**
             * Class A Value
             * @description Total monetary value of Class A products
             * @example 750000
             */
            class_a_value: number;
            /**
             * Class A Share Pct
             * @description Percentage share of total value for Class A
             * @example 78.5
             */
            class_a_share_pct: number;
            /**
             * Class B Count
             * @description Number of Class B products
             * @example 5
             */
            class_b_count: number;
            /**
             * Class B Value
             * @description Total monetary value of Class B products
             * @example 160000
             */
            class_b_value: number;
            /**
             * Class B Share Pct
             * @description Percentage share of total value for Class B
             * @example 16.5
             */
            class_b_share_pct: number;
            /**
             * Class C Count
             * @description Number of Class C products
             * @example 7
             */
            class_c_count: number;
            /**
             * Class C Value
             * @description Total monetary value of Class C products
             * @example 50000
             */
            class_c_value: number;
            /**
             * Class C Share Pct
             * @description Percentage share of total value for Class C
             * @example 5
             */
            class_c_share_pct: number;
        };
        /**
         * AnalysisResponse
         * @description Complete response payload for POST /analyze.
         */
        AnalysisResponse: {
            /** @description Upload and processing metadata */
            meta: components["schemas"]["MetaResponse"];
            /** @description Data cleaning report */
            cleaning: components["schemas"]["CleaningReportResponse"];
            /** @description Dataset statistical profile */
            profile: components["schemas"]["DatasetProfileResponse"];
            /** @description Overall dataset quality evaluation */
            quality: components["schemas"]["QualityScoreResponse"];
            /** @description Selected analysis columns and candidates */
            selection: components["schemas"]["ColumnSelectionResponse"];
            /** @description Product ranking and ABC/Pareto analysis */
            ranking: components["schemas"]["RankingResponse"];
            /** @description Period-over-period growth metrics */
            growth: components["schemas"]["GrowthResponse"];
            /** @description Chart-ready structured JSON data */
            charts: components["schemas"]["ChartsResponse"];
            /**
             * Warnings
             * @description Warnings and informational notices
             */
            warnings?: string[];
        };
        /** Body_analyze_data_analyze_post */
        Body_analyze_data_analyze_post: {
            /**
             * File
             * @description CSV (.csv) or Excel (.xlsx, .xls) file
             */
            file: string;
            /**
             * Product Column
             * @description Optional override column name for product/item entity
             */
            product_column?: string | null;
            /**
             * Value Column
             * @description Optional override column name for metric/revenue
             */
            value_column?: string | null;
            /**
             * Date Column
             * @description Optional override column name for date/timestamp
             */
            date_column?: string | null;
            /**
             * Top N
             * @description Number of top and bottom ranked products (1 to 50)
             * @default 10
             */
            top_n: number;
            /**
             * Sheet Name
             * @description Optional specific sheet name for Excel workbooks
             */
            sheet_name?: string | null;
        };
        /**
         * ChartsResponse
         * @description JSON-ready visualization datasets for charting libraries.
         */
        ChartsResponse: {
            /**
             * Top Products Bar
             * @description Top products and their values for bar chart
             */
            top_products_bar: components["schemas"]["TopProductBarItemResponse"][];
            /**
             * Pareto Curve
             * @description Ordered products with cumulative percentage for Pareto chart
             */
            pareto_curve: components["schemas"]["ParetoCurveItemResponse"][];
            /**
             * Abc Distribution
             * @description Product count and value share per ABC class
             */
            abc_distribution: components["schemas"]["ABCDistributionItemResponse"][];
            /**
             * Monthly Trend
             * @description Monthly value trend across time
             */
            monthly_trend: components["schemas"]["MonthlyTrendItemResponse"][];
            /**
             * Value Histogram
             * @description 10-bucket distribution histogram of the value metric
             */
            value_histogram: components["schemas"]["HistogramBucketResponse"][];
        };
        /**
         * CleaningReportResponse
         * @description Report detailing data cleaning and type coercion results.
         */
        CleaningReportResponse: {
            /**
             * Rows Before
             * @description Number of rows before cleaning
             * @example 619
             */
            rows_before: number;
            /**
             * Rows After
             * @description Number of rows after cleaning and dropping empty rows
             * @example 600
             */
            rows_after: number;
            /**
             * Rows Dropped
             * @description Count of empty rows removed
             * @example 19
             */
            rows_dropped: number;
            /**
             * Columns Dropped
             * @description List of empty column names removed
             * @example []
             */
            columns_dropped?: string[];
            /**
             * Conversions Performed
             * @description Summary descriptions of column type conversions
             * @example [
             *       "Converted column 'revenue' to numeric (600 valid values)"
             *     ]
             */
            conversions_performed?: string[];
            /**
             * Failed Numeric Conversions
             * @description Count of individual cells that failed numeric parsing
             * @example 0
             */
            failed_numeric_conversions: number;
            /**
             * Failed Date Conversions
             * @description Count of individual cells that failed date parsing
             * @example 0
             */
            failed_date_conversions: number;
            /**
             * Null Like Values Converted
             * @description Count of placeholder tokens (e.g., 'NA', '-') converted to missing
             * @example 12
             */
            null_like_values_converted: number;
        };
        /**
         * ColumnCandidateResponse
         * @description Candidate column considered for role selection.
         */
        ColumnCandidateResponse: {
            /**
             * Name
             * @description Column name
             * @example revenue
             */
            name: string;
            /**
             * Confidence
             * @description Selection confidence score from 0.0 to 1.0
             * @example 0.95
             */
            confidence: number;
            /**
             * Reason
             * @description Explanation of detection heuristic
             * @example Exact match on keyword 'revenue'
             */
            reason: string;
        };
        /**
         * ColumnProfileResponse
         * @description Statistical summary for an individual dataset column.
         */
        ColumnProfileResponse: {
            /**
             * Name
             * @description Column name
             * @example revenue
             */
            name: string;
            /**
             * Detected Type
             * @description Inferred data type (numeric, integer, date, categorical, text, boolean, id-like)
             * @example numeric
             */
            detected_type: string;
            /**
             * Missing Count
             * @description Count of missing/null cells in this column
             * @example 0
             */
            missing_count: number;
            /**
             * Missing Percent
             * @description Percentage of missing cells in this column
             * @example 0
             */
            missing_percent: number;
            /**
             * Unique Count
             * @description Number of distinct values in this column
             * @example 450
             */
            unique_count: number;
            /**
             * Sample Values
             * @description Sample representative values
             * @example [
             *       "2499.0",
             *       "698.0",
             *       "4998.0"
             *     ]
             */
            sample_values: string[];
            /**
             * Min
             * @description Minimum numeric value
             * @example 19
             */
            min?: number | null;
            /**
             * Max
             * @description Maximum numeric value
             * @example 24990
             */
            max?: number | null;
            /**
             * Mean
             * @description Mean numeric value
             * @example 1245.5
             */
            mean?: number | null;
            /**
             * Median
             * @description Median numeric value
             * @example 698
             */
            median?: number | null;
            /**
             * Std
             * @description Standard deviation
             * @example 850.25
             */
            std?: number | null;
            /**
             * Top Values
             * @description Top 5 most frequent values for categorical/text columns
             */
            top_values?: components["schemas"]["ValueCountResponse"][] | null;
        };
        /**
         * ColumnSelectionResponse
         * @description Identified entity, metric, and time columns with alternatives.
         */
        ColumnSelectionResponse: {
            /**
             * Product Column
             * @description Selected product/entity column
             * @example product
             */
            product_column: string;
            /**
             * Product Confidence
             * @description Confidence in product column selection
             * @example 0.95
             */
            product_confidence: number;
            /**
             * Product Candidates
             * @description Candidate product columns evaluated
             */
            product_candidates: components["schemas"]["ColumnCandidateResponse"][];
            /**
             * Value Column
             * @description Selected numeric value/metric column
             * @example revenue
             */
            value_column: string;
            /**
             * Value Confidence
             * @description Confidence in value column selection
             * @example 0.95
             */
            value_confidence: number;
            /**
             * Value Candidates
             * @description Candidate value columns evaluated
             */
            value_candidates: components["schemas"]["ColumnCandidateResponse"][];
            /**
             * Date Column
             * @description Selected date column if available
             * @example date
             */
            date_column?: string | null;
            /**
             * Date Confidence
             * @description Confidence in date column selection
             * @example 0.95
             */
            date_confidence?: number | null;
            /**
             * Date Candidates
             * @description Candidate date columns evaluated
             */
            date_candidates?: components["schemas"]["ColumnCandidateResponse"][];
            /**
             * Derived Revenue Created
             * @description True if revenue was automatically calculated from quantity * price
             * @default false
             * @example false
             */
            derived_revenue_created: boolean;
            /**
             * Notes
             * @description Column selection notes and derivation logs
             */
            notes?: string[];
        };
        /**
         * DatasetProfileResponse
         * @description Comprehensive dataset summary and per-column profile.
         */
        DatasetProfileResponse: {
            /**
             * Row Count
             * @description Total valid rows profiled
             * @example 600
             */
            row_count: number;
            /**
             * Column Count
             * @description Total columns profiled
             * @example 8
             */
            column_count: number;
            /**
             * Duplicate Row Count
             * @description Number of duplicate rows
             * @example 0
             */
            duplicate_row_count: number;
            /**
             * Total Missing Cells
             * @description Total missing values across the dataset
             * @example 5
             */
            total_missing_cells: number;
            /**
             * Data Quality Score
             * @description Dataset quality score (0-100)
             * @example 98.5
             */
            data_quality_score: number;
            /**
             * Columns
             * @description Profiles for every column in the dataset
             */
            columns: components["schemas"]["ColumnProfileResponse"][];
        };
        /**
         * GrowthResponse
         * @description Period-over-period growth trends per product.
         */
        GrowthResponse: {
            /**
             * Has Growth Data
             * @description True if sufficient time range was available to compute growth
             * @example true
             */
            has_growth_data: boolean;
            /**
             * Previous Period
             * @description Previous comparison period
             * @example 2025-11
             */
            previous_period?: string | null;
            /**
             * Latest Period
             * @description Latest comparison period
             * @example 2025-12
             */
            latest_period?: string | null;
            /**
             * Items
             * @description Per-product growth metrics
             */
            items?: components["schemas"]["ProductGrowthItemResponse"][];
            /**
             * Warning
             * @description Warning if growth could not be calculated
             */
            warning?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistogramBucketResponse
         * @description Histogram bucket item.
         */
        HistogramBucketResponse: {
            /**
             * Bucket Min
             * @description Lower bound of bucket
             * @example 0
             */
            bucket_min: number;
            /**
             * Bucket Max
             * @description Upper bound of bucket
             * @example 2500
             */
            bucket_max: number;
            /**
             * Label
             * @description Bucket display label
             * @example 0 - 2500
             */
            label: string;
            /**
             * Count
             * @description Count of rows falling into this bucket
             * @example 450
             */
            count: number;
        };
        /**
         * MetaResponse
         * @description Metadata about the processed file and request timing.
         */
        MetaResponse: {
            /**
             * Filename
             * @description Name of the uploaded file
             * @example sales_clean.csv
             */
            filename: string;
            /**
             * Rows
             * @description Total row count after initial load
             * @example 600
             */
            rows: number;
            /**
             * Columns
             * @description Total column count after initial load
             * @example 8
             */
            columns: number;
            /**
             * Processing Ms
             * @description Time taken to process and analyze data in milliseconds
             * @example 45.2
             */
            processing_ms: number;
            /**
             * Delimiter
             * @description Detected CSV delimiter (if applicable)
             * @example ,
             */
            delimiter?: string | null;
            /**
             * Sheet Name
             * @description Excel sheet parsed (if applicable)
             * @example Sheet1
             */
            sheet_name?: string | null;
        };
        /**
         * MonthlyTrendItemResponse
         * @description Chronological monthly trend item.
         */
        MonthlyTrendItemResponse: {
            /**
             * Month
             * @description Month (YYYY-MM)
             * @example 2025-01
             */
            month: string;
            /**
             * Value
             * @description Total metric value for month
             * @example 85000
             */
            value: number;
        };
        /**
         * ParetoCurveItemResponse
         * @description Pareto curve chart data item.
         */
        ParetoCurveItemResponse: {
            /**
             * Product
             * @description Product name
             * @example MacBook Pro 16
             */
            product: string;
            /**
             * Value
             * @description Product value
             * @example 450000
             */
            value: number;
            /**
             * Cumulative Pct
             * @description Cumulative percentage of total value
             * @example 35.5
             */
            cumulative_pct: number;
        };
        /**
         * ProductGrowthItemResponse
         * @description Product performance comparison between recent time periods.
         */
        ProductGrowthItemResponse: {
            /**
             * Product
             * @description Product name
             * @example MacBook Pro 16
             */
            product: string;
            /**
             * Previous Period
             * @description Previous period label (YYYY-MM)
             * @example 2025-11
             */
            previous_period: string;
            /**
             * Latest Period
             * @description Latest period label (YYYY-MM)
             * @example 2025-12
             */
            latest_period: string;
            /**
             * Previous Value
             * @description Value in previous period
             * @example 35000
             */
            previous_value: number;
            /**
             * Latest Value
             * @description Value in latest period
             * @example 42000
             */
            latest_value: number;
            /**
             * Change Pct
             * @description Percentage growth or decline
             * @example 20
             */
            change_pct: number;
            /**
             * Direction
             * @description Direction ('rising', 'falling', 'flat')
             * @example rising
             */
            direction: string;
        };
        /**
         * ProductRankItemResponse
         * @description Individual ranked product item with ABC classification.
         */
        ProductRankItemResponse: {
            /**
             * Rank
             * @description Descending rank position
             * @example 1
             */
            rank: number;
            /**
             * Product
             * @description Product name (canonical casing)
             * @example MacBook Pro 16
             */
            product: string;
            /**
             * Value
             * @description Total aggregated metric value
             * @example 450000
             */
            value: number;
            /**
             * Share Pct
             * @description Percentage share of total value
             * @example 35.5
             */
            share_pct: number;
            /**
             * Cumulative Pct
             * @description Cumulative value percentage including this item
             * @example 35.5
             */
            cumulative_pct: number;
            /**
             * Abc Class
             * @description ABC classification (A: <=80%, B: <=95%, C: >95%)
             * @example A
             */
            abc_class: string;
        };
        /**
         * QualityScoreResponse
         * @description Overall dataset data quality evaluation score.
         */
        QualityScoreResponse: {
            /**
             * Score
             * @description Data quality score from 0.0 to 100.0
             * @example 98.5
             */
            score: number;
            /**
             * Status
             * @description Quality rating level (Excellent, Good, Fair, Poor)
             * @example Excellent
             */
            status: string;
            /**
             * Duplicate Row Count
             * @description Count of exact duplicate rows detected
             * @example 0
             */
            duplicate_row_count: number;
            /**
             * Total Missing Cells
             * @description Total count of missing cells across all columns
             * @example 5
             */
            total_missing_cells: number;
            /**
             * Description
             * @description Explanation of quality score based on penalties
             * @example Dataset demonstrates high completeness and integrity.
             */
            description: string;
        };
        /**
         * RankingResponse
         * @description Comprehensive product ranking, ABC classification, and Pareto summary.
         */
        RankingResponse: {
            /**
             * Total Value
             * @description Total summed metric value across all products
             * @example 960000
             */
            total_value: number;
            /**
             * Product Count
             * @description Total distinct product count
             * @example 15
             */
            product_count: number;
            /**
             * Items
             * @description All ranked products sorted descending by value
             */
            items: components["schemas"]["ProductRankItemResponse"][];
            /**
             * Top N
             * @description Top N performing products
             */
            top_n: components["schemas"]["ProductRankItemResponse"][];
            /**
             * Bottom N
             * @description Bottom N performing products
             */
            bottom_n: components["schemas"]["ProductRankItemResponse"][];
            /**
             * Pareto Summary
             * @description Pareto summary sentence
             * @example 3 of 15 products (20.0%) generate 80% of the value
             */
            pareto_summary: string;
            /** @description Aggregated summary counts and shares by ABC class */
            abc_summary: components["schemas"]["ABCSummaryResponse"];
            /**
             * Missing Value Rows Count
             * @description Count of rows where value was missing/zero
             * @example 0
             */
            missing_value_rows_count: number;
            /**
             * Variants Merged Count
             * @description Count of product name casing/whitespace variants merged
             * @example 0
             */
            variants_merged_count: number;
            /**
             * Negative Value Products Count
             * @description Count of products with net negative values
             * @example 0
             */
            negative_value_products_count: number;
        };
        /**
         * TopProductBarItemResponse
         * @description Top product chart data item.
         */
        TopProductBarItemResponse: {
            /**
             * Product
             * @description Product name
             * @example MacBook Pro 16
             */
            product: string;
            /**
             * Value
             * @description Total value
             * @example 450000
             */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueCountResponse
         * @description Categorical value frequency item.
         */
        ValueCountResponse: {
            /**
             * Value
             * @description Categorical value label
             * @example Electronics
             */
            value: string;
            /**
             * Count
             * @description Frequency occurrence count
             * @example 120
             */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    analyze_data_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_data_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
